apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-vjmx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-vjmx
    app.kubernetes.io/part-of: build-suite-test-application-thck
  name: test-annotations-vjmx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-vjmx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-vjmx
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-relv-tenant/build-suite-test-application-thck/test-annotations-vjmx@sha256:9eff5b23172b3c45df8ede2de7e7144cac5caf9a781841b40be91104b0c45ba3
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
